// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Http = require("http");

var Http$1 = {};

Http.createServer(function (param, res) {
        return res.end("hello world");
      }).listen(3333);

exports.Http = Http$1;
/*  Not a pure module */
